# Generated by zshot-app scripts/release/update-homebrew-tap.sh — do not edit by hand.
cask "zshot" do
  version "0.33.0"
  sha256 "90915c837903e1d0f4a519432587e8a60426736a11be0928165270d80e38f45d"

  url "https://releases.zshot-app.com/download/ZShot-#{version}.dmg"
  name "ZShot"
  desc "Web page screenshot, render, and archival tool"
  homepage "https://zshot-app.com/"

  livecheck do
    url "https://zshot-app.com/appcast.xml"
    strategy :sparkle
  end

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :tahoe

  app "ZShot.app"
  # The CLI is a wrapper script that resolves symlinks to its physical
  # location and expects zshot_app.app as a sibling, so the link target is
  # the Application Support copy made by preflight below (mirroring what the
  # app's own CLIDownloadManager does on first launch).
  binary "#{Dir.home}/Library/Application Support/ZShot/zshot"

  preflight do
    support_dir = "#{Dir.home}/Library/Application Support/ZShot"
    resources = "#{staged_path}/ZShot.app/Contents/Resources"
    FileUtils.mkdir_p support_dir
    system_command "/usr/bin/ditto",
                   args: ["--noqtn", "#{resources}/zshot", "#{support_dir}/zshot"]
    system_command "/usr/bin/ditto",
                   args: ["--noqtn", "#{resources}/zshot_app.app", "#{support_dir}/zshot_app.app"]
  end

  zap trash: [
    "~/Library/Application Support/ZShot",
    "~/Library/Preferences/com.scaleassembly.zshot.plist",
  ]

  caveats <<~EOS
    To enable shell completions for the zshot CLI, add one line to your shell profile:

      bash   ~/.bashrc                    source <(zshot --completions bash)
      zsh    ~/.zshrc, after compinit     source <(zshot --completions zsh)
      fish   ~/.config/fish/config.fish   zshot --completions fish | source
  EOS
end
