# Generated by zshot-app scripts/release/update-homebrew-tap.sh — do not edit by hand.
cask "zshot" do
  version "0.21.2"
  sha256 "2ecfbc762290d1bea4db456bc05648d4c395f06f886d9d26c498b0962f765739"

  url "https://releases.zshot-app.com/download/ZShot-#{version}.dmg"
  name "ZShot"
  desc "Web page screenshot, render, and archival tool"
  homepage "https://zshot-app.com/"

  livecheck do
    url "https://zshot-app.com/appcast.xml"
    strategy :sparkle
  end

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :tahoe

  app "ZShot.app"
  # The CLI is a wrapper script that resolves symlinks to its physical
  # location and expects zshot_app.app as a sibling, so the link target is
  # the Application Support copy made by preflight below (mirroring what the
  # app's own CLIDownloadManager does on first launch).
  binary "#{Dir.home}/Library/Application Support/ZShot/zshot"

  preflight do
    support_dir = "#{Dir.home}/Library/Application Support/ZShot"
    resources = "#{staged_path}/ZShot.app/Contents/Resources"
    FileUtils.mkdir_p support_dir
    system_command "/usr/bin/ditto",
                   args: ["--noqtn", "#{resources}/zshot", "#{support_dir}/zshot"]
    system_command "/usr/bin/ditto",
                   args: ["--noqtn", "#{resources}/zshot_app.app", "#{support_dir}/zshot_app.app"]
  end

  zap trash: [
    "~/Library/Application Support/ZShot",
    "~/Library/Preferences/com.scaleassembly.zshot.plist",
  ]
end
